databases:
  - name: auxdio
    plan: free
    databaseName: auxdio
    user: auxdio

services:
  - type: web
    plan: free
    name: auxdio
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn auxdio.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: auxdio
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4